github.com:
    users:
        officialfindoraapp:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: officialfindoraapp
